#!/usr/bin/perl
# Conserve bandwidth - put a copy of Dilbert on your intranet.
# Run every morning with cron - after about 7am Eastern
########################################################
# Where do you want the image put?
# $dir = "c:/httpd/htdocs/Dilbert";
# These next 4 lines will change every time they change the
# page layout on the Dilbert site. Check back on my web site
# if things suddenly stop working
# Start with an index.html file containing ...
# <table border><tr>
# <!-- INSERT HERE -->
# </tr></table>
# ...
#  And whatever else you want on the page.
