require 'test/unit'
require File.dirname(__FILE__) + '/../test_helper.rb'
require File.dirname(__FILE__) + '/file_rule_test'
require File.dirname(__FILE__) + '/filename_rule_test'
require File.dirname(__FILE__) + '/keyword_rule_test'
require File.dirname(__FILE__) + '/rule_test'
require File.dirname(__FILE__) + '/definitions_test'
require File.dirname(__FILE__) + '/java_definitions_test'
require File.dirname(__FILE__) + '/dot_net_definitions_test'
require File.dirname(__FILE__) + '/jasper_definitions_test'
